# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: # Esto significa que el pipeline se va a ejecutar cuando se hagan cambios en la rama Master del repositotio
- master #

pool: # Es la maquina desde la cual se va a correr 
  vmImage: 'ubuntu-latest'

steps:  # Estos son los pasos que va correr el pipeline cada vez que se ejecute
- script: echo Hello, world!, Ximena
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
