trigger:
  - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: PrimerJob
        steps:
          - bash: echo Build PrimerJob
      - job: SegundoJob
        steps:
          - bash: echo Build SegundoJob
  - stage: DevDeploy
    jobs:  
      - job: DevDeployJob
        steps:
          - bash: echo PrimerJobDev
  - stage: QADeploy
    jobs:  
      - job: QADeployJob
        steps:
          - bash: echo PrimerJobQA  
  - stage: ProdDeploy
    jobs:  
      - job: ProdDeployJob
        steps:
          - bash: echo PrimerJobProd
