trigger:
  - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: PrimerJob
        steps:
        - bash: echo Build PrimerJob
    jobs:
      - job: PrimerJob
        steps:
        - bash: echo Build PrimerJob        
  - stage: DevDeploy
  - stage: QADeploy
  - stage: ProdDeploy
steps:
  - script: Paso1 Job1
    displayName: Run a one-line script
