trigger:
  - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: PrimerJob
        steps:
          - bash: echo Build PrimerJob
      - job: SegundoJob
        steps:
          - bash: echo Build SegundoJob
  - stage: DevDeploy
    dependsOn: Build
    jobs:  
      - job: DevDeployJob
        steps:
          - bash: echo PrimerJobDev
  - stage: QADeploy
    dependsOn: DevDeploy
    jobs:  
      - job: QADeployJob
        steps:
          - bash: echo PrimerJobQA  
  - stage: ProdDeploy
    dependsOn: QADeploy
    jobs:  
      - job: ProdDeployJob
        steps:
          - bash: echo PrimerJobProd
# al definir "Stages" le indicamos a nuestro proceso que se va a ejecutar por etapas
# Jobs es el siguiente en la jerarquias la cual maneja los Steps
#Steps son los pasos de cada job