

trigger: 
- master 

pool: 
  vmImage: 'ubuntu-latest'


jobs: 
- job: Job1 
  steps:  
  - script: echo soy el script del job 1
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2 
  dependsOn: Job1 #con esto determinamos que este job2 dependa del job1
  steps:  
  - script: echo soy el script del job 2
    displayName: 'Run a one-line script'
- job: Job3 
  dependsOn: Job2 #con esto determinamos que este job3 dependa del job2
  steps:  
  - script: echo soy el script del job 3
    displayName: 'Run a one-line script'
